# Generated by Django 4.0.2 on 2022-03-15 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_image_alter_article_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
